export const column = [
        {
            name: 'title',
            label: '标题',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'input',
                customType: '',
                dataType: 'STRING',
                props: {
                    isSearch: true,
                    required: false,
                    disabled: false,
                    fieldSearch: {
                        type: 'formSelect',
                        sort: 1,
                    },
                    hide: false,
                },
            },
        },
        {
            name: 'code',
            label: '编号',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'input',
                customType: '',
                dataType: 'STRING',
                props: {
                    hide: false,
                    isSearch: true,
                    required: false,
                    disabled: true,
                    fieldSearch: {
                        sort: 1,
                        type: 'formSelect',
                    },
                },
            },
        },
        {
            name: 'ownerId',
            label: '负责人',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'member',
                customType: '',
                dataType: 'STRING',
                props: {
                    limit: 1,
                    multiple: false,
                    collaboratorRoles: [
                        '-1',
                    ],
                },
            },
        },
        {
            name: 'issueStatus',
            label: '任务状态',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: true,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'groupSelect',
                customType: '',
                dataType: 'STRING',
                props: {
                    typeDisabled: true,
                    member: {
                        multiple: false,
                        required: false,
                    },
                    multiselect: {},
                    hide: false,
                    titleDisabled: true,
                    checked: true,
                    select: {},
                    groupSelect: {
                        groupOptions: [
                            {
                                children: [
                                    {
                                        color: '#E1E2E4',
                                        fontColor: '#5f5f5f',
                                        id: 7,
                                        parentId: 1,
                                        sort: 1,
                                        value: '未开始',
                                    },
                                ],
                                id: 1,
                                value: '未开始',
                            },
                            {
                                children: [
                                    {
                                        fontColor: '#377aff',
                                        id: 16,
                                        parentId: 2,
                                        sort: 2,
                                        value: '进行中',
                                        color: '#377AFF',
                                    },
                                ],
                                id: 2,
                                value: '进行中',
                            },
                            {
                                children: [
                                    {
                                        color: '#45CB7E',
                                        fontColor: '#54a944',
                                        id: 26,
                                        parentId: 3,
                                        sort: 3,
                                        value: '已完成',
                                    },
                                ],
                                id: 3,
                                value: '已完成',
                            },
                        ],
                        options: [
                            {
                                id: 7,
                                parentId: 1,
                                sort: 1,
                                value: '未开始',
                                color: '#E1E2E4',
                                fontColor: '#5f5f5f',
                            },
                            {
                                sort: 2,
                                value: '进行中',
                                color: '#377AFF',
                                fontColor: '#377aff',
                                id: 16,
                                parentId: 2,
                            },
                            {
                                value: '已完成',
                                color: '#45CB7E',
                                fontColor: '#54a944',
                                id: 26,
                                parentId: 3,
                                sort: 3,
                            },
                        ],
                    },
                    disabled: false,
                    isText: false,
                    required: true,
                    require: true,
                    inputnumber: {
                        accuracy: '',
                        percentage: false,
                        required: false,
                        thousandth: false,
                        unique: false,
                    },
                    aliasDisabled: false,
                    attrDisabled: false,
                },
            },
        },
        {
            name: 'planStartTime',
            label: '开始时间',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'datepicker',
                customType: '',
                dataType: 'STRING',
                props: {},
            },
        },
        {
            name: 'planEndTime',
            label: '截止时间',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'datepicker',
                customType: '',
                dataType: 'STRING',
                props: {},
            },
        },
        {
            name: 'remark',
            label: '描述',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'richtext',
                customType: '',
                dataType: 'STRING',
                props: {
                    member: {
                        multiple: false,
                        required: false,
                    },
                    multiselect: {},
                    required: false,
                    select: {},
                    inputnumber: {
                        thousandth: false,
                        unique: false,
                        accuracy: '',
                        percentage: false,
                        required: false,
                    },
                    isText: false,
                },
            },
        },
        {
            name: 'followerIds',
            label: '关注人',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'member',
                customType: '',
                dataType: 'STRING',
                props: {
                    collaboratorRoles: [
                        '-1',
                    ],
                    multiple: true,
                },
            },
        },
        {
            name: 'auditorIds',
            label: '确认人',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'member',
                customType: '',
                dataType: 'STRING',
                props: {
                    collaboratorRoles: [
                        '-1',
                    ],
                    multiple: true,
                },
            },
        },
        {
            name: 'projectObjectTypeId',
            label: '任务栏',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'select',
                customType: 'select',
                dataType: 'STRING',
                props: {
                    select: {},
                    titleDisabled: false,
                    typeDisabled: false,
                    disabled: false,
                    isText: true,
                    required: false,
                },
            },
        },
        {
            name: 'iterationId',
            label: '迭代',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'select',
                customType: 'select',
                dataType: 'STRING',
                props: {
                    required: true,
                    select: {},
                    titleDisabled: false,
                    typeDisabled: false,
                    disabled: false,
                    isText: false,
                },
            },
        },
        {
            name: 'projectId',
            label: '所属项目',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'select',
                customType: 'select',
                dataType: 'STRING',
                props: {
                    disabled: false,
                    isText: false,
                    required: true,
                    select: {},
                    titleDisabled: false,
                    typeDisabled: false,
                },
            },
        },
        {
            name: 'parentId',
            label: '父任务ID',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'input',
                customType: '',
                dataType: 'STRING',
                props: {
                    isSearch: true,
                    required: false,
                    disabled: true,
                    fieldSearch: {
                        type: 'formSelect',
                        sort: 1,
                    },
                    hide: true,
                },
            },
        },
        {
            name: '_field_priority',
            label: '优先级',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: true,
            writable: true,
            editable: true,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'select',
                customType: 'select',
                dataType: 'STRING',
                props: {
                    inputnumber: {
                        accuracy: '',
                        percentage: false,
                        required: false,
                        thousandth: false,
                        unique: false,
                    },
                    isText: false,
                    member: {
                        multiple: false,
                        required: false,
                    },
                    multiselect: {},
                    required: false,
                    select: {
                        options: [
                            {
                                value: '最高',
                                color: '#FF5037',
                                fontColor: '#FFFFFF',
                                id: 107298,
                            },
                            {
                                color: '#FFC700',
                                fontColor: '#FFFFFF',
                                id: 107299,
                                value: '较高',
                            },
                            {
                                id: 107300,
                                value: '普通',
                                color: '#67D287',
                                fontColor: '#FFFFFF',
                            },
                            {
                                color: '#5991FF',
                                fontColor: '#FFFFFF',
                                id: 107293,
                                value: '较低',
                            },
                            {
                                id: 107294,
                                value: '最低',
                                color: '#CACACA',
                                fontColor: '#FFFFFF',
                            },
                        ],
                    },
                },
            },
        },
        {
            name: 'document',
            label: '附件',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: true,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 0,
            field: {
                type: 'document',
                customType: '',
                dataType: 'CUSTOM',
                props: {
                    disabled: false,
                    hide: false,
                    multiple: false,
                    required: false,
                    checked: true,
                },
            },
        },
        {
            name: '_field_1661491790474',
            label: '数字',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: true,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 0,
            field: {
                type: 'inputnumber',
                customType: '',
                dataType: 'STRING',
                props: {
                    required: false,
                    disabled: false,
                    percentage: false,
                    accuracy: '1',
                    range: {},
                    collaboratorRoles: null,
                    thousandth: false,
                    inputnumber: {
                        accuracy: '1',
                        percentage: false,
                        range: {},
                        thousandth: false,
                    },
                    multiple: false,
                },
            },
        },
        {
            name: '_field_1661491797034',
            label: '货币',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: true,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 0,
            field: {
                type: 'amount',
                customType: '',
                dataType: 'STRING',
                props: {
                    amount: {
                        range: {},
                        sign: '￥',
                        accuracy: '1.0',
                        location: 'prefix',
                    },
                    range: {},
                    accuracy: '1.0',
                    disabled: false,
                    multiple: false,
                    required: false,
                    collaboratorRoles: null,
                    location: 'prefix',
                    sign: '￥',
                },
            },
        },
        {
            name: '_field_1663067791681',
            label: '智能公式',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: true,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 0,
            field: {
                type: 'input',
                customType: '',
                dataType: 'STRING',
                props: {
                    collaboratorRoles: null,
                    disabled: false,
                    multiple: false,
                    required: false,
                },
            },
        },
];

export type IColumn = typeof column;

export const dataSource = [
        {
            delFlag: 2,
            propertyId: 0,
            version: 1,
            endTime: '0001-01-01 00:00:00',
            planEndTime: '1970-01-01 00:00:00',
            issueId: 2460578,
            sort: '161253979230',
            projectObjectTypeId: 0,
            updator: {
                name: '赵嘉伟',
                avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                type: 'U_',
                status: 1,
                isDelete: 2,
                id: '1626780',
            },
            title: '1',
            appIds: [
                '1562424626585714690',
            ],
            collaborators: {
                followerIds: [
                    'U_1626780',
                ],
                auditorIds: [],
                ownerId: [
                    'U_1626780',
                ],
            },
            order: '3144286207',
            owner: 0,
            updateTime: '2022-09-13 19:16:39',
            code: '$83831-1',
            issueStatusType: 1,
            _field_1661491790474: 1,
            orgId: 14396,
            parentId: 0,
            createTime: '2022-08-24 22:12:32',
            creator: {
                type: 'U_',
                status: 1,
                isDelete: 2,
                id: '1626780',
                name: '赵嘉伟',
                avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
            },
            planStartTime: '1970-01-01 00:00:00',
            _field_1663067791681: '2',
            auditStatus: -1,
            ownerChangeTime: '2022-08-24 22:12:32',
            planWorkHour: 0,
            path: '0,',
            auditorIds: [],
            dataId: '1562442740858003458',
            moduleId: 0,
            isFiling: 0,
            projectId: 83831,
            status: 1,
            priorityId: 0,
            issueStatus: 7,
            iterationId: 0,
            recycleFlag: 2,
            id: 2460578,
            sourceId: 0,
            followerIds: [
                {
                    id: '1626780',
                    name: '赵嘉伟',
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                    type: 'U_',
                    status: 1,
                    isDelete: 2,
                },
            ],
            ownerId: [
                {
                    status: 1,
                    isDelete: 2,
                    id: '1626780',
                    name: '赵嘉伟',
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                    type: 'U_',
                },
            ],
            isDelete: 2,
            versionId: 0,
            issueObjectTypeId: 0,
            tableId: '1562424626938646528',
            remark: '',
            startTime: '0001-01-01 00:00:00',
            _field_1661491797034: 1,
        },
        {
            ownerId: [
                {
                    id: '1626780',
                    name: '赵嘉伟',
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                    type: 'U_',
                    status: 1,
                    isDelete: 2,
                },
            ],
            collaborators: {
                ownerId: [
                    'U_1626780',
                ],
                followerIds: [
                    'U_1626780',
                ],
                auditorIds: [],
            },
            creator: {
                isDelete: 2,
                id: '1626780',
                name: '赵嘉伟',
                avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                type: 'U_',
                status: 1,
            },
            issueId: 2460619,
            projectObjectTypeId: 0,
            planEndTime: '1970-01-01 00:00:00',
            _field_1661491790474: 2,
            title: '2',
            path: '0,',
            iterationId: 0,
            order: '3144220671',
            tableId: '1562424626938646528',
            id: 2460619,
            recycleFlag: 2,
            version: 1,
            appIds: [
                '1562424626585714690',
            ],
            isFiling: 0,
            auditStatus: -1,
            status: 1,
            ownerChangeTime: '2022-08-24 22:21:40',
            remark: '',
            delFlag: 2,
            owner: 0,
            _field_1661491797034: 2,
            isDelete: 2,
            planWorkHour: 0,
            moduleId: 0,
            propertyId: 0,
            sort: '161256666165',
            updator: {
                name: '赵嘉伟',
                avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                type: 'U_',
                status: 1,
                isDelete: 2,
                id: '1626780',
            },
            projectId: 83831,
            startTime: '0001-01-01 00:00:00',
            issueStatus: 7,
            versionId: 0,
            issueObjectTypeId: 0,
            dataId: '1562445039671123969',
            followerIds: [
                {
                    id: '1626780',
                    name: '赵嘉伟',
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                    type: 'U_',
                    status: 1,
                    isDelete: 2,
                },
            ],
            code: '$83831-2',
            orgId: 14396,
            priorityId: 0,
            auditorIds: [],
            planStartTime: '1970-01-01 00:00:00',
            createTime: '2022-08-24 22:21:40',
            endTime: '0001-01-01 00:00:00',
            sourceId: 0,
            updateTime: '2022-09-13 19:16:41',
            parentId: 0,
            _field_1663067791681: '4',
            issueStatusType: 1,
        },
    ];

export type IDataSource = typeof dataSource;
