export const column = [
        {
            name: 'title',
            label: '标题',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'input',
                customType: '',
                dataType: 'STRING',
                props: {
                    disabled: false,
                    fieldSearch: {
                        sort: 1,
                        type: 'formSelect',
                    },
                    hide: false,
                    isSearch: true,
                    required: false,
                },
            },
        },
        {
            name: 'code',
            label: '编号',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'input',
                customType: '',
                dataType: 'STRING',
                props: {
                    required: false,
                    disabled: true,
                    fieldSearch: {
                        sort: 1,
                        type: 'formSelect',
                    },
                    hide: false,
                    isSearch: true,
                },
            },
        },
        {
            name: 'ownerId',
            label: '负责人',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: true,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'member',
                customType: '',
                dataType: 'STRING',
                props: {
                    titleDisabled: true,
                    aliasDisabled: false,
                    limit: 1,
                    attrDisabled: true,
                    hide: false,
                    isCollaborators: true,
                    collaboratorRoles: [
                        '1562424626732388355',
                    ],
                    multiple: true,
                    checked: true,
                    disabled: false,
                    member: {
                        multiple: true,
                        collaboratorRoles: '1562424626732388355',
                        isCollaborators: true,
                    },
                    typeDisabled: true,
                },
            },
        },
        {
            name: 'issueStatus',
            label: '任务状态',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: true,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'groupSelect',
                customType: '',
                dataType: 'STRING',
                props: {
                    require: true,
                    groupSelect: {
                        groupOptions: [
                            {
                                value: '未开始',
                                children: [
                                    {
                                        value: '未开始',
                                        color: '#E1E2E4',
                                        fontColor: '#5f5f5f',
                                        id: 7,
                                        parentId: 1,
                                        sort: 1,
                                    },
                                ],
                                id: 1,
                            },
                            {
                                children: [
                                    {
                                        parentId: 2,
                                        sort: 2,
                                        value: '进行中',
                                        color: '#377AFF',
                                        fontColor: '#377aff',
                                        id: 16,
                                    },
                                ],
                                id: 2,
                                value: '进行中',
                            },
                            {
                                id: 3,
                                value: '已完成',
                                children: [
                                    {
                                        value: '已完成',
                                        color: '#45CB7E',
                                        fontColor: '#54a944',
                                        id: 26,
                                        parentId: 3,
                                        sort: 3,
                                    },
                                ],
                            },
                        ],
                        options: [
                            {
                                color: '#E1E2E4',
                                fontColor: '#5f5f5f',
                                id: 7,
                                parentId: 1,
                                sort: 1,
                                value: '未开始',
                            },
                            {
                                id: 16,
                                parentId: 2,
                                sort: 2,
                                value: '进行中',
                                color: '#377AFF',
                                fontColor: '#377aff',
                            },
                            {
                                parentId: 3,
                                sort: 3,
                                value: '已完成',
                                color: '#45CB7E',
                                fontColor: '#54a944',
                                id: 26,
                            },
                        ],
                    },
                    titleDisabled: true,
                    disabled: false,
                    required: true,
                    multiselect: {},
                    typeDisabled: true,
                    aliasDisabled: false,
                    inputnumber: {
                        accuracy: '',
                        percentage: false,
                        required: false,
                        thousandth: false,
                        unique: false,
                    },
                    checked: true,
                    attrDisabled: false,
                    member: {
                        multiple: false,
                        required: false,
                    },
                    select: {},
                    isText: false,
                    hide: false,
                },
            },
        },
        {
            name: 'planStartTime',
            label: '开始时间',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'datepicker',
                customType: '',
                dataType: 'STRING',
                props: {},
            },
        },
        {
            name: 'planEndTime',
            label: '截止时间',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'datepicker',
                customType: '',
                dataType: 'STRING',
                props: {},
            },
        },
        {
            name: 'remark',
            label: '描述',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'richtext',
                customType: '',
                dataType: 'STRING',
                props: {
                    multiselect: {},
                    required: false,
                    select: {},
                    inputnumber: {
                        required: false,
                        thousandth: false,
                        unique: false,
                        accuracy: '',
                        percentage: false,
                    },
                    isText: false,
                    member: {
                        multiple: false,
                        required: false,
                    },
                },
            },
        },
        {
            name: 'followerIds',
            label: '关注人',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'member',
                customType: '',
                dataType: 'STRING',
                props: {
                    collaboratorRoles: [
                        '-1',
                    ],
                    multiple: true,
                },
            },
        },
        {
            name: 'auditorIds',
            label: '确认人',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'member',
                customType: '',
                dataType: 'STRING',
                props: {
                    multiple: true,
                    collaboratorRoles: [
                        '-1',
                    ],
                },
            },
        },
        {
            name: 'projectObjectTypeId',
            label: '任务栏',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'select',
                customType: 'select',
                dataType: 'STRING',
                props: {
                    disabled: false,
                    isText: true,
                    required: false,
                    select: {},
                    titleDisabled: false,
                    typeDisabled: false,
                },
            },
        },
        {
            name: 'iterationId',
            label: '迭代',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'select',
                customType: 'select',
                dataType: 'STRING',
                props: {
                    titleDisabled: false,
                    typeDisabled: false,
                    disabled: false,
                    isText: false,
                    required: true,
                    select: {},
                },
            },
        },
        {
            name: 'projectId',
            label: '所属项目',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'select',
                customType: 'select',
                dataType: 'STRING',
                props: {
                    select: {},
                    titleDisabled: false,
                    typeDisabled: false,
                    disabled: false,
                    isText: false,
                    required: true,
                },
            },
        },
        {
            name: 'parentId',
            label: '父任务ID',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: false,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'input',
                customType: '',
                dataType: 'STRING',
                props: {
                    isSearch: true,
                    required: false,
                    disabled: true,
                    fieldSearch: {
                        sort: 1,
                        type: 'formSelect',
                    },
                    hide: true,
                },
            },
        },
        {
            name: '_field_priority',
            label: '优先级',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: true,
            writable: true,
            editable: true,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 2,
            field: {
                type: 'select',
                customType: 'select',
                dataType: 'STRING',
                props: {
                    isText: false,
                    member: {
                        required: false,
                        multiple: false,
                    },
                    multiselect: {},
                    required: false,
                    select: {
                        options: [
                            {
                                id: 107298,
                                value: '最高',
                                color: '#FF5037',
                                fontColor: '#FFFFFF',
                            },
                            {
                                fontColor: '#FFFFFF',
                                id: 107299,
                                value: '较高',
                                color: '#FFC700',
                            },
                            {
                                color: '#67D287',
                                fontColor: '#FFFFFF',
                                id: 107300,
                                value: '普通',
                            },
                            {
                                id: 107293,
                                value: '较低',
                                color: '#5991FF',
                                fontColor: '#FFFFFF',
                            },
                            {
                                value: '最低',
                                color: '#CACACA',
                                fontColor: '#FFFFFF',
                                id: 107294,
                            },
                        ],
                    },
                    inputnumber: {
                        required: false,
                        thousandth: false,
                        unique: false,
                        accuracy: '',
                        percentage: false,
                    },
                },
            },
        },
        {
            name: 'document',
            label: '附件',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: true,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 0,
            field: {
                type: 'document',
                customType: '',
                dataType: 'CUSTOM',
                props: {
                    checked: true,
                    disabled: false,
                    hide: false,
                    multiple: false,
                    required: false,
                },
            },
        },
        {
            name: '_field_1661491790474',
            label: '数字',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: true,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 0,
            field: {
                type: 'inputnumber',
                customType: '',
                dataType: 'STRING',
                props: {
                    multiple: false,
                    required: false,
                    accuracy: '1',
                    disabled: false,
                    collaboratorRoles: null,
                    percentage: false,
                    thousandth: false,
                    inputnumber: {
                        accuracy: '1',
                        percentage: false,
                        range: {},
                        thousandth: false,
                    },
                    range: {},
                },
            },
        },
        {
            name: '_field_1661491797034',
            label: '货币',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: true,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 0,
            field: {
                type: 'amount',
                customType: '',
                dataType: 'STRING',
                props: {
                    required: false,
                    accuracy: '1.0',
                    amount: {
                        accuracy: '1.0',
                        location: 'prefix',
                        range: {},
                        sign: '￥',
                    },
                    location: 'prefix',
                    range: {},
                    disabled: false,
                    multiple: false,
                    collaboratorRoles: null,
                    sign: '￥',
                },
            },
        },
        {
            name: '_field_1663067791681',
            label: '智能公式',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: true,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 0,
            field: {
                type: 'input',
                customType: '',
                dataType: 'STRING',
                props: {
                    disabled: false,
                    multiple: false,
                    required: false,
                    collaboratorRoles: null,
                },
            },
        },
        {
            name: 'baRelating',
            label: '前后置',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: true,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 0,
            field: {
                type: 'baRelating',
                customType: '',
                dataType: 'STRING',
                props: {
                    multiple: false,
                    required: false,
                    collaboratorRoles: null,
                    disabled: false,
                },
            },
        },
        {
            name: 'workHour',
            label: '工时',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: true,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 0,
            field: {
                type: 'workHour',
                customType: '',
                dataType: 'CUSTOM',
                props: {
                    disabled: false,
                    multiple: false,
                    required: false,
                    workHour: {},
                    collaboratorRoles: null,
                },
            },
        },
        {
            name: '_field_1663240891242',
            label: '我的自定义',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: true,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 0,
            field: {
                type: 'member',
                customType: '',
                dataType: 'STRING',
                props: {
                    collaboratorRoles: null,
                    disabled: false,
                    isCollaborators: false,
                    member: {
                        isCollaborators: false,
                        multiple: false,
                    },
                    multiple: false,
                    required: false,
                },
            },
        },
        {
            name: '_field_1663241850031',
            label: '部门',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: true,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 0,
            field: {
                type: 'dept',
                customType: '',
                dataType: 'STRING',
                props: {
                    required: false,
                    collaboratorRoles: null,
                    dept: {
                        multiple: false,
                    },
                    disabled: false,
                    multiple: false,
                },
            },
        },
        {
            name: '_field_1663244206628',
            label: '多选',
            aliasTitle: '',
            description: '',
            isSys: false,
            isOrg: false,
            writable: true,
            editable: true,
            unique: false,
            uniquePreHandler: '',
            sensitiveStrategy: '',
            sensitiveFlag: 0,
            field: {
                type: 'multiselect',
                customType: '',
                dataType: 'STRING',
                props: {
                    multiple: false,
                    multiselect: {
                        options: [
                            {
                                color: '#377AFF',
                                id: 244220945,
                                value: '1',
                            },
                            {
                                color: '#4FBBEF',
                                id: 244222706,
                                value: '2',
                            },
                        ],
                    },
                    options: [
                        {
                            color: '#377AFF',
                            id: 244220945,
                            value: '1',
                        },
                        {
                            value: '2',
                            color: '#4FBBEF',
                            id: 244222706,
                        },
                    ],
                    required: false,
                    checked: true,
                    collaboratorRoles: null,
                    disabled: false,
                    hide: false,
                },
            },
        },
    ];
export type IColumn = typeof column;

export const dataSource = [
        {
            isDelete: 2,
            version: 1,
            code: '$83831-1',
            updator: {
                type: 'U_',
                status: 1,
                isDelete: 2,
                id: '1626780',
                name: '赵嘉伟',
                avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
            },
            endTime: '2022-09-15 19:20:14',
            status: 1,
            updateTime: '2022-09-15 20:17:35',
            recycleFlag: 2,
            _field_1663241850031: [
                {
                    status: 1,
                    isDelete: 2,
                    id: '13592474',
                    name: '测试',
                    avatar: '',
                    type: 'D_',
                },
            ],
            remark: '',
            isFiling: 0,
            issueObjectTypeId: 0,
            delFlag: 2,
            ownerId: [
                {
                    isDelete: 2,
                    id: '1626780',
                    name: '赵嘉伟',
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                    type: 'U_',
                    status: 1,
                },
                {
                    isDelete: 2,
                    id: '1315032',
                    name: '蒋长仁',
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_46cce5f7-b56d-4223-8d3a-b39da532180g~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                    type: 'U_',
                    status: 1,
                },
                {
                    id: '1111980',
                    name: '苏汉宇',
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_ce196b4b-ea30-4c50-9a95-68b25129448g~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                    type: 'U_',
                    status: 1,
                    isDelete: 2,
                },
            ],
            auditorIds: [],
            auditStatus: -1,
            _field_1663244206628: [
                244220945,
                244222706,
            ],
            title: '1',
            dataId: '1562442740858003458',
            followerIds: [
                {
                    name: '赵嘉伟',
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                    type: 'U_',
                    status: 1,
                    isDelete: 2,
                    id: '1626780',
                },
            ],
            tableId: '1562424626938646528',
            planWorkHour: 0,
            collaborators: {
                followerIds: [
                    'U_1626780',
                ],
                auditorIds: [],
                ownerId: [
                    'U_1626780',
                    'U_1315032',
                    'U_1111980',
                ],
            },
            order: '3144286207',
            _field_1661491797034: 1,
            id: 2460578,
            ownerChangeTime: '2022-08-24 22:12:32',
            _field_1663240891242: [
                {
                    id: '1315032',
                    name: '蒋长仁',
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_46cce5f7-b56d-4223-8d3a-b39da532180g~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                    type: 'U_',
                    status: 1,
                    isDelete: 2,
                },
            ],
            iterationId: 0,
            issueId: 2460578,
            baRelating: {
                linkTo: [
                    '1562445039671123969',
                    '1570255347585294337',
                ],
                linkFrom: [
                    '1562445039671123969',
                ],
            },
            planEndTime: '2022-09-18 18:00:00',
            sourceId: 0,
            sort: '161253979230',
            path: '0,',
            moduleId: 0,
            issueStatusType: 3,
            workHour: {
                collaboratorIds: [
                    'U_1626780',
                ],
                actualHour: '0',
                planHour: '24',
            },
            planStartTime: '2022-09-15 09:00:00',
            versionId: 0,
            appIds: [
                '1562424626585714690',
            ],
            createTime: '2022-08-24 22:12:32',
            creator: {
                avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                type: 'U_',
                status: 1,
                isDelete: 2,
                id: '1626780',
                name: '赵嘉伟',
            },
            projectObjectTypeId: 0,
            projectId: 83831,
            _field_1661491790474: 1,
            orgId: 14396,
            issueStatus: 26,
            startTime: '2022-09-15 19:20:12',
            owner: 0,
            priorityId: 0,
            propertyId: 0,
            parentId: 0,
            _field_1663067791681: '2',
        },
        {
            sort: '161256666165',
            appIds: [
                '1562424626585714690',
            ],
            remark: '',
            status: 1,
            delFlag: 2,
            planWorkHour: 0,
            id: 2460619,
            sourceId: 0,
            order: '3144220671',
            code: '$83831-2',
            _field_1661491797034: 2,
            _field_1663244206628: [
                244222706,
            ],
            tableId: '1562424626938646528',
            issueStatusType: 2,
            _field_1663240891242: [
                {
                    id: '1626780',
                    name: '赵嘉伟',
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                    type: 'U_',
                    status: 1,
                    isDelete: 2,
                },
            ],
            moduleId: 0,
            auditStatus: -1,
            ownerId: [
                {
                    id: '1626780',
                    name: '赵嘉伟',
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                    type: 'U_',
                    status: 1,
                    isDelete: 2,
                },
            ],
            versionId: 0,
            issueId: 2460619,
            isDelete: 2,
            startTime: '2022-09-15 19:20:26',
            iterationId: 0,
            creator: {
                status: 1,
                isDelete: 2,
                id: '1626780',
                name: '赵嘉伟',
                avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                type: 'U_',
            },
            ownerChangeTime: '2022-08-24 22:21:40',
            collaborators: {
                followerIds: [
                    'U_1626780',
                ],
                auditorIds: [],
                ownerId: [
                    'U_1626780',
                ],
            },
            auditorIds: [],
            _field_1663241850031: [
                {
                    name: '广告',
                    avatar: '',
                    type: 'D_',
                    status: 1,
                    isDelete: 2,
                    id: '13769443',
                },
            ],
            parentId: 0,
            createTime: '2022-08-24 22:21:40',
            endTime: '1970-01-01 00:00:00',
            priorityId: 0,
            planStartTime: '2022-09-24 09:00:00',
            followerIds: [
                {
                    name: '赵嘉伟',
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                    type: 'U_',
                    status: 1,
                    isDelete: 2,
                    id: '1626780',
                },
            ],
            _field_1661491790474: 2,
            title: '2',
            path: '0,',
            propertyId: 0,
            owner: 0,
            issueObjectTypeId: 0,
            orgId: 14396,
            updateTime: '2022-09-15 20:17:09',
            baRelating: {
                linkTo: [
                    '1562442740858003458',
                ],
                linkFrom: [
                    '1562442740858003458',
                ],
            },
            updator: {
                id: '1626780',
                name: '赵嘉伟',
                avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                type: 'U_',
                status: 1,
                isDelete: 2,
            },
            recycleFlag: 2,
            version: 1,
            projectId: 83831,
            issueStatus: 16,
            isFiling: 0,
            projectObjectTypeId: 0,
            _field_1663067791681: '4',
            planEndTime: '2022-09-30 18:00:00',
            dataId: '1562445039671123969',
        },
        {
            delFlag: 2,
            orgId: 14396,
            priorityId: 0,
            path: '0,',
            auditorIds: [],
            dataId: '1570255347585294337',
            code: '$83831-3',
            owner: 0,
            planStartTime: '2022-09-18 09:00:00',
            appIds: [
                '1562424626585714690',
            ],
            createTime: '2022-09-15 11:37:03',
            issueStatusType: 1,
            issueId: 2566982,
            recycleFlag: 2,
            _field_1663241850031: [
                {
                    type: 'D_',
                    status: 1,
                    isDelete: 2,
                    id: '13774271',
                    name: '总裁办',
                    avatar: '',
                },
            ],
            baRelating: {
                linkFrom: [
                    '1562442740858003458',
                ],
            },
            parentId: 0,
            sourceId: 0,
            title: '设计大咖十六点',
            moduleId: 0,
            propertyId: 0,
            order: '3144155135',
            isDelete: 2,
            tableId: '1562424626938646528',
            status: 1,
            ownerChangeTime: '2022-09-15 11:37:03',
            collaborators: {
                followerIds: [
                    'U_1626780',
                ],
                auditorIds: [],
                ownerId: [
                    'U_1626780',
                    'U_1111980',
                    'U_1111849',
                    'U_1112176',
                    'U_1245323',
                    'U_1294074',
                ],
            },
            startTime: '0001-01-01 00:00:00',
            projectObjectTypeId: 0,
            versionId: 0,
            endTime: '0001-01-01 00:00:00',
            remark: '',
            ownerId: [
                {
                    name: '赵嘉伟',
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                    type: 'U_',
                    status: 1,
                    isDelete: 2,
                    id: '1626780',
                },
                {
                    name: '苏汉宇',
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_ce196b4b-ea30-4c50-9a95-68b25129448g~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                    type: 'U_',
                    status: 1,
                    isDelete: 2,
                    id: '1111980',
                },
                {
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_1cdb65a6-0e83-44d3-9bc3-977b2369bd0g~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                    type: 'U_',
                    status: 1,
                    isDelete: 2,
                    id: '1111849',
                    name: '李国威🎈🎈🎈🎈🎈🎈🎈',
                },
                {
                    id: '1112176',
                    name: '杨燕🎨',
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_905a1cf4-9385-47de-8d86-be4d237611cg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                    type: 'U_',
                    status: 1,
                    isDelete: 2,
                },
                {
                    name: '牟联兵',
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_360b0235-c48b-4653-8247-f79bf346dc1g~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                    type: 'U_',
                    status: 1,
                    isDelete: 2,
                    id: '1245323',
                },
                {
                    name: '罗丹丹',
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_c9470281-c179-444b-a915-bd8a7b87cd3g~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                    type: 'U_',
                    status: 1,
                    isDelete: 2,
                    id: '1294074',
                },
            ],
            iterationId: 0,
            creator: {
                avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                type: 'U_',
                status: 1,
                isDelete: 2,
                id: '1626780',
                name: '赵嘉伟',
            },
            sort: '168227165370',
            auditStatus: -1,
            followerIds: [
                {
                    type: 'U_',
                    status: 1,
                    isDelete: 2,
                    id: '1626780',
                    name: '赵嘉伟',
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                },
            ],
            planWorkHour: 0,
            issueStatus: 7,
            updateTime: '2022-09-15 20:17:42',
            isFiling: 0,
            planEndTime: '2022-09-30 18:00:00',
            projectId: 83831,
            id: 2566982,
            version: 1,
            issueObjectTypeId: 0,
            updator: {
                isDelete: 2,
                id: '1626780',
                name: '赵嘉伟',
                avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_71fd6fdb-dbd9-413c-8f39-39b994a45edg~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                type: 'U_',
                status: 1,
            },
            _field_1663240891242: [
                {
                    id: '1111849',
                    name: '李国威🎈🎈🎈🎈🎈🎈🎈',
                    avatar: 'https://s1-imfile.feishucdn.com/static-resource/v1/v2_1cdb65a6-0e83-44d3-9bc3-977b2369bd0g~?image_size=noop&cut_type=&quality=&format=png&sticker_format=.webp',
                    type: 'U_',
                    status: 1,
                    isDelete: 2,
                },
            ],
        },
    ];

export type IDataSource = typeof dataSource;
